spring:
#  profiles:
#    include: oauth
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true


logging.level:
  org.hibernate.SQL: debug

## 머스태치 + 스프링 부트 3.7xx 한글깨짐 방지
server:                       
  servlet:
    encoding:
      force-response: true 